name: dotnet package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration ExportPlugin --no-restore --property:OutputPath="./addons/yarnspinner_godot/lib"
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: build dotnet
          title: Build Dotnet
          body: Build dotnet solution to plugin bin folder
          branch: build-dotnet
